"""Customer Master + extra field library for Chart of Group Master ticks."""

from __future__ import annotations

from typing import Any


INDIA_STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
]

INVESTMENT_KINDS = [
    "Property",
    "Shares",
    "Mutual Fund",
    "Fixed Deposit",
    "Gold",
    "Other",
]

WHEN_PROPERTY = {"investment_kind": ["Property"]}

INDIA_LAND_UNITS = [
    "Sq. Ft.",
    "Sq. Yd. (Gaj)",
    "Sq. Mt.",
    "Sq. Km.",
    "Acre",
    "Hectare",
    "Are",
    "Centiare",
    "Bigha",
    "Pucca Bigha",
    "Kaccha Bigha",
    "Biswa",
    "Biswansi",
    "Katha (Kattha)",
    "Dhur",
    "Dismil (Decimal)",
    "Kanal",
    "Marla",
    "Killa",
    "Guntha (Gunta)",
    "Cent",
    "Ground",
    "Ankanam",
    "Nali",
    "Mutthi",
    "Lecha",
    "Chatak",
    "Karam",
    "Satak",
    "Percent",
    "Vigha",
    "Kani",
    "Ghumaon",
]


def _f(
    key: str,
    label: str,
    *,
    section: str,
    field_type: str = "text",
    source: str = "customer",
    locked: bool = True,
    always_on: bool = False,
    always_required: bool = False,
    maxlength: int | None = None,
    options: list | None = None,
    features: list | None = None,
    hint: str = "",
    label_template: str = "",
    tier: str = "basic",
    db: str = "",
    visible_when: dict | None = None,
    visible_when_any: dict | None = None,
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "section": section,
        "type": field_type,
        "source": source,
        "locked": locked,
        "always_on": always_on,
        "always_required": always_required,
        "maxlength": maxlength,
        "options": options or [],
        "features": features or [],
        "hint": hint,
        "label_template": label_template or label,
        "tier": tier,
        "db": db,
        "required": always_required,
        "visible_when": visible_when or {},
        "visible_when_any": visible_when_any or {},
    }


def _prop(
    key: str,
    label: str,
    *,
    field_type: str = "text",
    maxlength: int | None = None,
    options: list | None = None,
    features: list | None = None,
    hint: str = "",
    visible_when: dict | None = None,
    visible_when_any: dict | None = None,
) -> dict[str, Any]:
    return _f(
        key,
        label,
        section="property",
        field_type=field_type,
        source="property",
        locked=True,
        maxlength=maxlength,
        options=options,
        features=features,
        hint=hint,
        visible_when=visible_when if visible_when is not None else dict(WHEN_PROPERTY),
        visible_when_any=visible_when_any,
    )


# Built-in Customer Master fields the user can tick per Chart of Account Group.
# customer_name is always on the form and always mandatory.
CUSTOMER_FIELD_LIBRARY: list[dict[str, Any]] = [
    _f("customer_name", "Customer Name", section="basic", always_on=True, always_required=True, maxlength=200),
    _f("customer_type", "Customer Type", section="basic", field_type="select"),
    _f("customer_status", "Status", section="basic", field_type="select"),
    _f("father_husband_name", "Father / Husband Name", section="basic", maxlength=200),
    _f("company_firm_name", "Company / Firm Name", section="basic", maxlength=200),
    _f("date_of_birth", "Date of Birth", section="basic", field_type="date"),
    _f("date_of_incorporation", "Date of Incorporation", section="basic", field_type="date"),
    _f("gender", "Gender", section="basic", field_type="select"),
    _f("occupation", "Occupation", section="basic", maxlength=100),
    _f("remarks", "Remarks", section="basic", field_type="textarea", maxlength=1000),
    _f("opening_balance", "Opening Balance", section="basic", field_type="number"),
    _f("opening_balance_date", "Opening Balance Date", section="basic", field_type="date"),
    _f("opening_balance_dr_cr", "Opening Balance Dr / Cr", section="basic", field_type="select"),
    _f("mobile_number", "Mobile Number", section="contact", maxlength=20),
    _f("alternate_mobile", "Alternate Mobile", section="contact", maxlength=20),
    _f("whatsapp_number", "WhatsApp Number", section="contact", maxlength=20),
    _f("email_id", "Email ID", section="contact", field_type="email", maxlength=200),
    _f("website", "Website", section="contact", maxlength=300),
    _f("pincode", "Pincode", section="address", maxlength=6),
    _f("country", "Country", section="address", field_type="select"),
    _f("state", "State", section="address", maxlength=100),
    _f("state_gst_code", "State GST Code", section="address", maxlength=2),
    _f("district", "District", section="address", maxlength=100),
    _f("city", "City", section="address", maxlength=100),
    _f("address_line1", "Address Line 1", section="address", maxlength=300),
    _f("address_line2", "Address Line 2", section="address", maxlength=300),
    _f("village", "Village", section="address", maxlength=100),
    _f("area", "Area", section="address", maxlength=100),
    _f("pan_number", "PAN Number", section="address", maxlength=10),
    _f("aadhaar_number", "Aadhaar Number", section="address", maxlength=12),
    _f("income_tax_password", "Income Tax Password", section="itr", maxlength=20),
    _f("passport_number", "Passport Number", section="itr", maxlength=30),
    _f("voter_id_number", "Voter ID Number", section="itr", maxlength=30),
    _f("ration_card_number", "Ration Card Number", section="itr", maxlength=30),
    _f("pran_number", "PRAN Number", section="itr", maxlength=30),
    _f("tan_number", "TAN Number", section="tds", maxlength=20),
    _f("gst_number", "GST Number", section="gst", maxlength=20),
    _f("filing_frequency", "Filing Frequency", section="gst", field_type="select"),
    _f("driving_license_number", "Driving License Number", section="dsc", maxlength=30),
    _f("cin_number", "CIN Number", section="gst", maxlength=30),
    _f("msme_registration_number", "MSME Registration Number", section="business", maxlength=50),
    _f("udyam_registration_number", "UDYAM Registration Number", section="business", maxlength=50),
    _f("llpin_number", "LLPIN Number", section="business", maxlength=30),
    _f("shop_act_license_number", "Shop Act License Number", section="business", maxlength=50),
    _f("trade_license_number", "Trade License Number", section="business", maxlength=50),
    _f("labour_license_number", "Labour License Number", section="business", maxlength=50),
    _f("pf_establishment_number", "PF Establishment Number", section="compliance", maxlength=50),
    _f("esic_registration_number", "ESIC Registration Number", section="compliance", maxlength=50),
    _f("professional_tax_number", "Professional Tax Number", section="compliance", maxlength=50),
    _f("epfo_code", "EPFO Code", section="compliance", maxlength=50),
    _f("bank_name", "Bank Name", section="bank", maxlength=150),
    _f("branch_name", "Branch Name", section="bank", maxlength=150),
    _f("account_holder_name", "Account Holder Name", section="bank", maxlength=200),
    _f("account_number", "Account Number", section="bank", maxlength=50),
    _f("ifsc_code", "IFSC Code", section="bank", maxlength=20),
    _f("facebook", "Facebook", section="social", maxlength=300),
    _f("instagram", "Instagram", section="social", maxlength=300),
    _f("twitter_x", "Twitter / X", section="social", maxlength=300),
    _f("linkedin", "LinkedIn", section="social", maxlength=300),
    _f("youtube", "YouTube", section="social", maxlength=300),
    _f(
        "purchase_date",
        "Purchase Date",
        section="extra",
        field_type="date",
        source="extra",
        locked=True,
        label_template="{entity} Purchase Date",
        db="PurchaseDate",
    ),
    _f(
        "depreciation_rate",
        "Depreciation Rate",
        section="extra",
        field_type="percent",
        source="extra",
        locked=True,
        features=[],
        hint="Enter the depreciation rate (%) manually.",
        tier="advanced",
        db="DepreciationRate",
    ),
    _f(
        "appreciation_rate",
        "Appreciation Rate",
        section="extra",
        field_type="percent",
        source="extra",
        locked=True,
        hint="Posts to P&L income and increases Balance Sheet value when date, rate, and opening are set.",
        tier="advanced",
        db="AppreciationRate",
    ),
    _prop(
        "investment_kind",
        "Investment Type",
        field_type="select",
        options=INVESTMENT_KINDS,
        visible_when={},
    ),
    _prop(
        "property_state",
        "State",
        field_type="select",
        features=["india_loc:states"],
    ),
    _prop(
        "property_district",
        "District",
        field_type="select",
        features=["india_loc:districts"],
    ),
    _prop(
        "property_tehsil",
        "Tehsil / Taluka",
        field_type="select",
        features=["india_loc:talukas"],
    ),
    _prop(
        "property_pincode",
        "Pincode",
        field_type="select",
        features=["india_loc:pincodes"],
    ),
    _prop(
        "property_village",
        "Village / Area",
        field_type="select",
        features=["india_loc:places"],
    ),
    _prop(
        "property_land_area",
        "Land Area",
        field_type="number",
        hint="Defaults to 1.",
    ),
    _prop(
        "property_land_unit",
        "Land Unit",
        field_type="select",
        options=INDIA_LAND_UNITS,
        hint="Defaults to Sq. Ft.",
    ),
    _prop(
        "property_land_value",
        "Land Purchase Value",
        field_type="money",
        features=["land_value_sync"],
        hint="Public circle rate × land area. Fills Opening Balance on the master.",
    ),
]

SECTION_LABELS = {
    "basic": "Basic Info",
    "contact": "Contact",
    "address": "Address",
    "itr": "ITR Details",
    "tds": "TDS Details",
    "gst": "GST Details",
    "dsc": "DSC Details",
    "business": "Business Registration",
    "compliance": "Compliance",
    "bank": "Bank Details",
    "social": "Social Media",
    "extra": "Asset / Investment",
    "property": "Property Location (India)",
    "custom": "Custom Fields",
}

# Ticking a field in Chart of Group Master also ticks these related fields.
_PROPERTY_LOCATION_CORE = (
    "investment_kind",
    "property_state",
    "property_district",
    "property_tehsil",
    "property_pincode",
    "property_village",
)

FIELD_LINKS: dict[str, tuple[str, ...]] = {
    "pincode": ("country", "state", "district", "city", "state_gst_code"),
    "state": ("country",),
    "district": ("country", "state"),
    "city": ("country", "state", "district"),
    "state_gst_code": ("country", "state"),
    "village": ("country", "state", "district", "pincode"),
    "area": ("country", "state", "district", "city", "pincode"),
    "address_line1": ("country", "state", "district", "city", "pincode"),
    "address_line2": ("address_line1", "country", "state", "district", "city", "pincode"),
    "gst_number": ("country", "state", "state_gst_code"),
    "ifsc_code": ("bank_name", "branch_name"),
    "account_number": ("bank_name", "account_holder_name", "ifsc_code", "branch_name"),
    "branch_name": ("bank_name",),
    "opening_balance": ("opening_balance_date", "opening_balance_dr_cr"),
    "opening_balance_date": ("opening_balance_dr_cr",),
    "depreciation_rate": ("purchase_date",),
    "appreciation_rate": ("purchase_date",),
    "property_state": (
        "investment_kind",
        "property_district",
        "property_tehsil",
        "property_pincode",
        "property_village",
    ),
    "property_district": (
        "investment_kind",
        "property_state",
        "property_tehsil",
        "property_pincode",
        "property_village",
    ),
    "property_tehsil": (
        "investment_kind",
        "property_state",
        "property_district",
        "property_pincode",
        "property_village",
    ),
    "property_pincode": (
        "investment_kind",
        "property_state",
        "property_district",
        "property_tehsil",
        "property_village",
    ),
    "property_village": _PROPERTY_LOCATION_CORE,
    "property_land_area": ("investment_kind", "property_land_unit"),
    "property_land_unit": ("investment_kind", "property_land_area"),
    "property_land_value": _PROPERTY_LOCATION_CORE
    + ("property_land_area", "property_land_unit", "opening_balance", "opening_balance_date", "opening_balance_dr_cr"),
}

LIBRARY_BY_KEY = {row["key"]: row for row in CUSTOMER_FIELD_LIBRARY}

PROPERTY_FIELD_KEYS = tuple(
    row["key"] for row in CUSTOMER_FIELD_LIBRARY if row.get("section") == "property"
)

SKIP_DYN_RENDER = frozenset({"customer_name", "customer_group"})
EAV_SOURCES = frozenset({"custom", "property"})
