"""Additional Help topics (masters, accounting, CRM, HR, admin)."""

from __future__ import annotations

from app.services.help_catalog import HelpTopic, _f, _s, _shot, _t

MORE_TOPICS: tuple[HelpTopic, ...] = (
    _t(
        "customer-master",
        "Customer Master",
        "bi-people",
        "masters",
        "Masters → Customer Master",
        "Party master used by stamp, followups, invoices, and ledgers. Opening balance, GSTIN, PAN, group, and asset class (where enabled) all start here.",
        url="/masters/customer",
        steps=(
            _s("Add or edit a customer", "Enter name, mobile, PAN/GSTIN, and group. Save before using the party on an activity."),
            _s("Opening balance", "Opening amount + Dr/Cr and opening date feed customer ledger and outstanding."),
            _s("Asset class", "When shown, asset class is used on financial grouping — it does not change invoice tax."),
        ),
        shots=(
            _shot(
                "Figure 1 — Customer Master row",
                "Customer Master",
                ribbon=("Masters", "Customer Master"),
                columns=("Name", "Mobile", "PAN", "Opening", "Group"),
                rows=(("Sharma Enterprises", "9876543210", "ABCDE1234F", "25,000.00 Dr", "Sundry Debtors"),),
            ),
        ),
        formulas=(
            _f("Customer opening", "Signed opening as on Opening Balance Date (Dr increases receivable)."),
        ),
        related=("group-master", "outstanding", "invoices", "chart-of-account"),
        keywords="customer master pan gstin opening",
    ),
    _t(
        "group-master",
        "Customer Group Master",
        "bi-collection",
        "masters",
        "Masters → Group Master",
        "Groups customers for outstanding and reporting. Does not post amounts by itself.",
        url="/masters/group",
        related=("customer-master",),
        keywords="customer group master",
    ),
    _t(
        "bank-master",
        "Bank Master",
        "bi-bank",
        "masters",
        "Masters → Bank Master",
        "Cash, bank, OD, and RD accounts. Opening balance and opening date are the book starting point. Account type comes from Account Type Master. QR / UPI fields support invoice collection.",
        url="/masters/bank",
        steps=(
            _s("Add an account", "Name, account number, type (Cash / Bank / OD / RD), opening balance, opening date."),
            _s("Display order", "Controls how accounts appear on dashboards and pickers."),
            _s("QR / bill received", "Optional UPI QR for public invoice pay links."),
        ),
        shots=(
            _shot(
                "Figure 1 — Bank Master",
                "Bank Master",
                columns=("Account", "Type", "Opening", "Opening date"),
                rows=(("HDFC Current", "Bank", "2,00,000.00 Dr", "01-04-2026"), ("Cash", "Cash", "15,000.00 Dr", "01-04-2026")),
                highlights=("Opening is as on Opening date", "Later transactions never rewrite this opening"),
            ),
        ),
        formulas=(
            _f("Bank book", "Movements dated on or after Opening Balance Date are applied; earlier dates are ignored for running balance."),
        ),
        related=("account-type-master", "ledger-report", "bank-cash-transactions"),
        keywords="bank master cash od rd opening qr",
    ),
    _t(
        "account-type-master",
        "Account Type Master",
        "bi-tags",
        "masters",
        "Masters → Account Type Master",
        "Codes used on Bank Master (Current, OD, Cash, RD, and any custom type). Changing a type later updates how the book is classified, not historical voucher amounts.",
        url="/masters/account-type",
        related=("bank-master",),
        keywords="account type master",
    ),
    _t(
        "work-category-master",
        "Work / Category Master",
        "bi-briefcase",
        "masters",
        "Masters → Work/Category Master",
        "Income and expense heads used on Income/Expense activity, invoices, and P&L grouping. Map each head to Chart of Account groups.",
        url="/masters/income-expense",
        steps=(
            _s("Add a head", "Name the work/category and mark income vs expense."),
            _s("Link accounting group", "Chart of Account / Chart of Group assignment drives Financial Statements."),
        ),
        shots=(
            _shot(
                "Figure 1 — Work/Category list",
                "Work/Category Master",
                columns=("Name", "Income/Expense", "Group"),
                rows=(("Consultancy", "Income", "Direct Income"), ("Office rent", "Expense", "Indirect Expenses")),
            ),
        ),
        related=("sub-work-master", "chart-of-account", "income-expense"),
        keywords="work category income expense head",
    ),
    _t(
        "sub-work-master",
        "Sub Work Master",
        "bi-diagram-2",
        "masters",
        "Masters → Sub Work Master",
        "Optional sub-heads under a work/category (for example GSTR-1 under GST).",
        url="/masters/sub-work",
        related=("work-category-master",),
        keywords="sub work master",
    ),
    _t(
        "item-master",
        "Item Master",
        "bi-box-seam",
        "masters",
        "Masters → Item Master",
        "Stock, service (SAC), and fixed-asset items. GST rates, HSN/SAC, opening, depreciation rate (typed, not synced), and investment appreciation / land value live here.",
        url="/masters/item",
        steps=(
            _s("GST item", "Set HSN/SAC, GST %, and sale/purchase rates for invoices."),
            _s("Fixed asset", "Enter purchase/put-to-use date, opening WDV, and depreciation %. The Depreciation Chart uses these values. There is no rate Sync button — type the % from Appendix I yourself."),
            _s("Land / investment", "Land-value or appreciation fields (where shown) affect investment ledgers, not WDV depreciation."),
        ),
        shots=(
            _shot(
                "Figure 1 — Fixed asset on Item Master",
                "Item Master",
                ribbon=("Masters", "Item Master"),
                fields=(
                    ("Item", "Office car"),
                    ("HSN", "8703"),
                    ("Depreciation %", "15.00"),
                    ("Opening WDV", "8,00,000.00"),
                    ("Put to use", "12-06-2024"),
                ),
                highlights=("Type depreciation % manually", "Chart reads these fields; it does not overwrite them on open"),
            ),
        ),
        formulas=(
            _f("Invoice taxable", "Qty × rate (or service amount) before GST."),
            _f("WDV inputs", "Opening WDV and rate on this master are the only inputs to the Depreciation Chart."),
        ),
        related=("depreciation-chart", "invoices", "fixed-assets-schedule"),
        keywords="item master hsn sac gst depreciation land appreciation",
    ),
    _t(
        "chart-of-group",
        "Chart of Group Master",
        "bi-diagram-3",
        "masters",
        "Masters → Chart of Group Master",
        "Tally-style groups (Assets, Liabilities, Income, Expense and their children). Nature (Dr/Cr normal) drives ledger running balances.",
        url="/masters/chart-group",
        steps=(
            _s("Create a group", "Name, parent/under, and nature (Asset, Liability, Income, Expense)."),
            _s("Use on accounts", "Chart of Account Master assigns ledgers into these groups (up to five roles: Sale, Purchase, Income, Expense, Contra)."),
        ),
        shots=(
            _shot(
                "Figure 1 — Chart of Group",
                "Chart of Group Master",
                columns=("Group", "Under", "Nature"),
                rows=(("Sundry Debtors", "Current Assets", "Asset"), ("Sales", "Direct Income", "Income")),
            ),
        ),
        formulas=(
            _f("Group nature", "Asset/Expense close +Dr−Cr. Liability/Income close +Cr−Dr."),
        ),
        related=("chart-of-account", "trial-balance"),
        keywords="chart of group tally nature",
    ),
    _t(
        "chart-of-account",
        "Chart of Account Master",
        "bi-journal",
        "masters",
        "Masters → Chart of Account Master",
        "Lists Customer Master and Work/Category names as ledgers and lets you assign Chart of Group. Manual accounts (for example Cash) can be added. Names from masters are not edited here.",
        url="/masters/chart-account",
        steps=(
            _s("Search", "Filter by customer or work name."),
            _s("Assign groups", "Edit a row and select up to five groups (Sale / Purchase / Income / Expense / Contra)."),
            _s("Add manual", "Use Add when the ledger does not come from a master."),
        ),
        shots=(
            _shot(
                "Figure 1 — Chart of Account grid",
                "Chart of Account Master",
                ribbon=("Masters", "Chart of Account Master"),
                columns=("Source", "Account Name", "Group", "Status"),
                rows=(("Customer", "Sharma Enterprises", "Sundry Debtors", "Active"), ("Manual", "Cash", "Cash-in-hand", "Active")),
            ),
        ),
        related=("chart-of-group", "customer-master", "financial-statements"),
        keywords="chart of account ledger group assign",
    ),
    _t(
        "followup-masters",
        "Followup Master",
        "bi-diagram-3",
        "masters",
        "Masters → Followup Master",
        "Workflow stages for ITR, DSC, TDS, and GST followup screens. Changing a stage name updates the activity grid; it does not recalculate old bills.",
        url="/masters/followup/itr",
        steps=(
            _s("Pick the module", "ITR / DSC / TDS / GST each have their own stage list."),
            _s("Order stages", "Display order is the left-to-right pipeline on the activity."),
        ),
        related=("itr-followup", "dsc-followup", "gst-followup", "tds-followup"),
        keywords="followup master workflow stages",
    ),
    _t(
        "purpose-master",
        "Purpose Master",
        "bi-flag",
        "masters",
        "Masters → Purpose Master",
        "Purpose codes used on bank/cash contra and similar vouchers.",
        url="/masters/purpose",
        related=("bank-cash-transactions",),
        keywords="purpose master",
    ),
    _t(
        "credentials-master",
        "Credentials Master",
        "bi-key",
        "masters",
        "Masters → Credentials Master",
        "Store portal user ids (ITD, GST, etc.) against a customer. Passwords are handled per the screen rules — this is a register, not a posting module.",
        url="/masters/credentials",
        related=("customer-master",),
        keywords="credentials master portal login",
        audience="Staff with Masters access",
    ),
    _t(
        "invoices",
        "Invoices",
        "bi-receipt",
        "accounting",
        "Accounting → Invoices",
        "Purchase, sale/service, and other vouchers. Lines use Item Master (HSN/SAC and GST). Payments can use bank QR / public UPI pay links.",
        url="/accounting/invoice",
        steps=(
            _s("Open the hub", "Accounting → Invoices. Choose Purchase, Sale/Service, or Other."),
            _s("Header", "Party (Customer Master), date, place of supply (intra vs inter GST)."),
            _s("Lines", "Select items, quantity/amount, and tax. Service items can carry quarter months for review."),
            _s("Save and print", "Preview GST invoice PDF. Record receipt against the invoice to reduce outstanding."),
        ),
        shots=(
            _shot(
                "Figure 1 — Sale invoice header and tax footer",
                "Invoices",
                ribbon=("Accounting", "Invoices"),
                fields=(("Party", "Sharma Enterprises"), ("Date", "09-09-2026"), ("Place of supply", "Uttarakhand")),
                columns=("Item", "Taxable", "GST", "Total"),
                rows=(("ITR filing (SAC 9982)", "5,000.00", "900.00", "5,900.00"),),
                highlights=("GST follows item rate and place of supply", "Receipts reduce customer outstanding"),
            ),
        ),
        formulas=(
            _f("Taxable value", "Line amount before tax (qty × rate, or service amount)."),
            _f("GST", "Intra-state: CGST + SGST = Taxable × rate. Inter-state: IGST = Taxable × rate."),
            _f("Invoice total", "Taxable + GST − discounts (as on the voucher)."),
            _f("Outstanding effect", "Sale bills increase customer billed; receipts increase credit."),
        ),
        related=("item-master", "customer-master", "outstanding", "accounting-reports"),
        keywords="invoice gst cgst sgst igst sale purchase",
    ),
    _t(
        "accounting-reports",
        "Accounting Reports",
        "bi-file-bar-graph",
        "accounting",
        "Accounting → Reports",
        "Invoice registers and related accounting listings. Books and statements remain under Reports and Analysis.",
        url="/accounting/reports",
        related=("invoices", "ledger-report"),
        keywords="accounting reports invoice register",
    ),
    _t(
        "crm-overview",
        "CRM",
        "bi-people",
        "crm",
        "CRM",
        "Leads, opportunities, tasks, follow-ups, calendar, analytics, and Communication Center (WhatsApp, email, website inbox).",
        url="/crm/dashboard",
        steps=(
            _s("Dashboard", "CRM → Dashboard for pipeline counts."),
            _s("Leads to opportunities", "Capture a lead, qualify, then convert to an opportunity."),
            _s("Communication Center", "Open inboxes by channel. Templates live under WhatsApp Templates."),
        ),
        shots=(
            _shot(
                "Figure 1 — CRM dashboard tiles",
                "CRM",
                ribbon=("CRM", "Dashboard"),
                columns=("Tile", "Count"),
                rows=(("Open leads", "14"), ("Overdue follow-ups", "3"), ("WhatsApp unread", "6")),
            ),
        ),
        related=("communication-center", "crm-leads", "customer-master"),
        keywords="crm leads opportunities tasks",
    ),
    _t(
        "communication-center",
        "Communication Center",
        "bi-chat-dots",
        "crm",
        "CRM → Communication Center",
        "Unified inbox: WhatsApp, Email, SMS, Website contact, AI chatbot (where enabled), call logs, and WhatsApp templates.",
        url="/crm/inbox",
        steps=(
            _s("Pick a channel", "Use the Communication Center children or /crm/inbox?channel=WhatsApp."),
            _s("Reply", "Open a thread and send from the configured integration (see Integration Settings)."),
        ),
        shots=(
            _shot(
                "Figure 1 — WhatsApp inbox",
                "WhatsApp Inbox",
                columns=("Contact", "Last message", "Status"),
                rows=(("9876543210", "Please share ITR acknowledgement", "Open"),),
            ),
        ),
        related=("crm-overview", "integration-settings"),
        keywords="whatsapp inbox email sms website chatbot",
    ),
    _t(
        "crm-leads",
        "Leads, opportunities, and tasks",
        "bi-person-plus",
        "crm",
        "CRM → Leads / Opportunities / Tasks",
        "Lead capture, opportunity value, and task reminders. Customer 360 and Timeline show the same party history.",
        url="/crm/leads",
        related=("crm-overview", "customer-master"),
        keywords="leads opportunities tasks customer 360 timeline",
    ),
    _t(
        "public-report-ration-fps",
        "Ration Card Detail Report for FPS",
        "bi-shop-window",
        "public",
        "Public Report → Ration Card Report → Ration Card Detail Report for FPS",
        "Search or add a ration dealer, import the NFSA CSV onto the grid, then download an A4 portrait PDF grouped by Scheme Name + RC Number. Phone uses a mobile PDF; desktop uses a desktop PDF.",
        url="/public-report/ration-card/fps-detail",
        steps=(
            _s("Select dealer", "Search the ration dealer. If the master already has the shop, Select and Edit appear, then FPS ID search opens."),
            _s("Add if missing", "If search finds nothing, use Add on the same screen. Save the dealer, then Select it."),
            _s("Import CSV", "Browse the NFSA ration-card CSV and click Import CSV. Members appear on the grid sorted by Scheme Name and RC Number."),
            _s("A4 PDF", "Click A4 PDF. The file is A4 portrait. On a phone it uses the mobile layout; on a computer it uses the desktop layout."),
        ),
        shots=(
            _shot(
                "Figure 1 — Dealer search, FPS ID, and CSV browse",
                "Ration Card Detail Report for FPS",
                ribbon=("Public Report", "Ration Card Report", "Ration Card Detail Report for FPS"),
                fields=(("Dealer", "Ramesh Chandra Pinaro"), ("FPS ID", "FPS2026030500000011931"), ("CSV", "ramesh chandra pinaro.csv")),
                columns=("Full Name", "Scheme Name", "RC Number"),
                rows=(("Khimuli Devi", "AAY", "RC010510000012957"), ("Madhavi Devi", "AAY", "RC010510000021622")),
            ),
        ),
        tips=(
            "Excel often prefixes IDs with an apostrophe; the import strips that automatically.",
            "Use A4 PDF after import. Phone download is a mobile PDF; desktop download is a desktop PDF. Both are A4 portrait.",
        ),
        keywords="ration card fps dealer nfsa aay phh tehsil public report",
    ),
    _t(
        "public-report-pds-masters",
        "Ration Card masters (Uttarakhand)",
        "bi-diagram-3",
        "public",
        "Public Report → Ration Card Report → State / District / DSO / ARO / FPS / Ration Card Master",
        "Hierarchy masters for PDS geography and shops. Uttarakhand state and 13 districts import from the FPS Excel dump; other states can be added later by hand. DSO / ARO / FPS / ration cards are entered here. After save, codes stay locked and must stay unique.",
        url="/public-report/ration-card/state-master",
        steps=(
            _s("State / District", "Uttarakhand and its districts are seeded once. Add another state later from State Master if needed. Codes cannot be edited after save."),
            _s("Offices", "DSO is under District. ARO is under DSO. FPS is under ARO. One DSO office row is created per district as a starting point."),
            _s("FPS / cards", "FPS Master sits under District (optional DSO / ARO). Ration Card Master sits under FPS. Use Add, Edit, or Delete on each screen."),
        ),
        related=("public-report-ration-fps",),
        keywords="pds state district dso aro fps ration card uttarakhand master",
    ),
    _t(
        "hr-overview",
        "HR",
        "bi-person-badge",
        "hr",
        "HR",
        "Recruitment and employee files: jobs, applications, pipeline, interviews, employees, letters, and HR reports. Most HR screens require Administrator.",
        url="/hr/dashboard",
        audience="Administrator",
        steps=(
            _s("Dashboard", "HR → Dashboard for funnel KPIs."),
            _s("Applications", "Filter by search and status. Open a row for interview and offer actions."),
            _s("Employees", "Employee Master, directory, documents, timeline, probation."),
            _s("Letters", "Offer and appointment letters from templates."),
        ),
        shots=(
            _shot(
                "Figure 1 — HR ribbon",
                "HR Dashboard",
                ribbon=("Dashboard", "Applications", "Pipeline", "Employees", "Actions"),
                columns=("KPI", "Value"),
                rows=(("Open jobs", "3"), ("New applications", "11"), ("Interviews this week", "4")),
            ),
        ),
        related=("hr-recruitment", "recruitment-admin"),
        keywords="hr recruitment employees offers probation",
    ),
    _t(
        "hr-recruitment",
        "Recruitment pipeline",
        "bi-kanban",
        "hr",
        "HR → Applications / Pipeline / Interviews",
        "Move candidates from application to interview to selected. Website recruitment applications also appear under Admin Role → Recruitment.",
        url="/hr/applications",
        audience="Administrator",
        related=("hr-overview", "recruitment-admin"),
        keywords="pipeline interviews selected candidates",
    ),
    _t(
        "admin-dashboard",
        "Admin Dashboard",
        "bi-speedometer",
        "admin",
        "Admin Role → Admin Dashboard",
        "Administrator home for user activity and operational counts. Not the same as the main Dashboard.",
        url="/admin/dashboard",
        audience="Administrator",
        related=("users-admin", "customer-activity"),
        keywords="admin dashboard",
    ),
    _t(
        "users-admin",
        "Users",
        "bi-person-gear",
        "admin",
        "Admin Role → Users",
        "Create staff users and assign roles (Operator, Viewer, Manager, Admin, CA, Accountant, and others). Role controls ribbon items. Help is always available after sign-in.",
        url="/admin/users",
        audience="Administrator",
        steps=(
            _s("Add a user", "User id, name, role(s), and password policy as on the form."),
            _s("Roles", "Administrator/Admin see all Admin Role tools. Manager/Operator/Viewer also see Data Backup. Everyone sees Help."),
        ),
        shots=(
            _shot(
                "Figure 1 — Users list",
                "Users",
                columns=("User ID", "Name", "Role"),
                rows=(("admin", "Administrator", "Administrator"), ("op1", "Front office", "Operator")),
            ),
        ),
        related=("ribbon-navigation", "data-backup"),
        keywords="users roles operator admin",
    ),
    _t(
        "menu-customization",
        "Menu Customization",
        "bi-sliders",
        "admin",
        "Admin Role → Menu Customization",
        "Rename, hide, restyle, or add ribbon items. Do not remove Admin Role or Dashboard. Legacy modules stay blocked.",
        url="/admin/menu-customization",
        audience="Administrator",
        tips=("Help is seeded automatically; keep its URL /help so all roles can open it.",),
        related=("ribbon-navigation",),
        keywords="menu customization font color",
    ),
    _t(
        "data-backup",
        "Data Backup",
        "bi-database-down",
        "admin",
        "Admin Role → Data Backup",
        "Database backup for Administrator, Admin, Manager, Operator, and Viewer. Other Admin Role tools stay hidden for those staff roles.",
        url="/admin/backup/data",
        audience="Administrator, Admin, Manager, Operator, Viewer",
        steps=(
            _s("Run Data Backup", "Follow the on-screen path. Store the file outside the PC when possible."),
            _s("Restore", "Restore Backup is Administrator-only and is a different menu."),
        ),
        shots=(
            _shot(
                "Figure 1 — Data Backup action",
                "Data Backup",
                ribbon=("Admin Role", "Data Backup"),
                fields=(("Last backup", "08-09-2026 18:40"),),
                highlights=("Available to Manager / Operator / Viewer", "Does not change ledgers"),
            ),
        ),
        related=("backup-full", "restore-backup"),
        keywords="data backup database bak",
    ),
    _t(
        "backup-full",
        "Backup Full",
        "bi-database-fill",
        "admin",
        "Admin Role → Backup Full",
        "Full application + database ZIP. Administrator only.",
        url="/admin/backup/full",
        audience="Administrator",
        related=("data-backup", "restore-backup"),
        keywords="backup full zip",
    ),
    _t(
        "restore-backup",
        "Restore Backup",
        "bi-arrow-counterclockwise",
        "admin",
        "Admin Role → Restore Backup",
        "Restore a VPS or local backup onto this PC. Administrator only. This overwrites data — take a fresh backup first.",
        url="/admin/backup/restore",
        audience="Administrator",
        related=("data-backup", "backup-full"),
        keywords="restore backup",
    ),
    _t(
        "utility",
        "Utility",
        "bi-tools",
        "admin",
        "Admin Role → Utility",
        "Local/VPS sync, clear cache, system health, and app info. Labels flip depending on whether you are on the local PC or the VPS.",
        url="/admin/utility",
        audience="Administrator",
        steps=(
            _s("Sync", "Upload VPS locally / Download Local on VPS — push or pull deploy files."),
            _s("Clear cache", "Clears Python/template caches after a deploy."),
            _s("Health / App Info", "Database and runtime checks; paths and mode."),
        ),
        related=("system-health", "software-updates"),
        keywords="utility sync cache vps",
    ),
    _t(
        "system-health",
        "System Health",
        "bi-heart-pulse",
        "admin",
        "Admin Role → System Health / Utility → Health",
        "Mission Control: database, disk, and public health checks. Dashboard shows a banner when a check fails.",
        url="/admin/system-health",
        audience="Administrator",
        related=("utility", "dashboard"),
        keywords="system health mission control",
    ),
    _t(
        "software-updates",
        "Software Updates",
        "bi-arrow-repeat",
        "admin",
        "Admin Role → Software Updates",
        "Application version, change log, and deployment history.",
        url="/admin/software-updates",
        audience="Administrator",
        related=("about-software",),
        keywords="software updates version changelog",
    ),
    _t(
        "about-software",
        "About Software",
        "bi-info-circle",
        "admin",
        "Admin Role → About Software",
        "Current build, database version, and release notes.",
        url="/admin/about-software",
        related=("software-updates",),
        keywords="about software version",
    ),
    _t(
        "customer-activity",
        "Customer Activity (admin)",
        "bi-activity",
        "admin",
        "Admin Role → Customer Activity",
        "Administrator view of client/customer portal activity.",
        url="/admin/customer-activity",
        audience="Administrator",
        related=("customer-portal", "users-admin"),
        keywords="customer activity portal",
    ),
    _t(
        "customer-portal",
        "Customer portal",
        "bi-person-badge",
        "start",
        "Customer portal (clients)",
        "Clients sign in at /customer to see their profile and limited data. Staff continue to use the ERP ribbon.",
        url="/customer",
        audience="Clients (portal) and staff who support them",
        related=("customer-master", "customer-activity"),
        keywords="customer portal login",
    ),
    _t(
        "seo-keywords",
        "SEO Keywords",
        "bi-search",
        "admin",
        "Admin Role → SEO Keywords",
        "Keywords published to the marketing website API.",
        url="/admin/seo",
        audience="Administrator",
        related=("website-analytics",),
        keywords="seo keywords",
    ),
    _t(
        "website-analytics",
        "Website Analytics",
        "bi-graph-up-arrow",
        "admin",
        "Admin Role → Website Analytics",
        "Visitor ingest from the public site. Read-only analytics for administrators.",
        url="/admin/website-analytics",
        audience="Administrator",
        related=("seo-keywords", "communication-center"),
        keywords="website analytics visitors",
    ),
    _t(
        "estamp-orders",
        "eStamp orders",
        "bi-file-earmark",
        "admin",
        "Admin Role → eStamp orders",
        "Orders received from the public eStamp API. Fulfilment still happens in Stamp Activity.",
        url="/admin/estamp-orders",
        audience="All staff",
        related=("stamp-activity",),
        keywords="estamp orders api",
    ),
    _t(
        "dsc-orders",
        "DSC orders",
        "bi-shield",
        "admin",
        "Admin Role → DSC orders",
        "Orders received from the public DSC API. Track fulfilment in DSC Followup.",
        url="/admin/dsc-orders",
        audience="Administrator",
        related=("dsc-followup",),
        keywords="dsc orders api",
    ),
    _t(
        "recruitment-admin",
        "Recruitment applications (website)",
        "bi-file-earmark-person",
        "admin",
        "Admin Role → Recruitment",
        "Applications submitted from the public website, reviewed here and in HR.",
        url="/admin/recruitment",
        audience="Administrator",
        related=("hr-recruitment",),
        keywords="recruitment applications website",
    ),
    _t(
        "property-admin",
        "Property Management",
        "bi-houses",
        "admin",
        "Admin Role → Property Management",
        "Property listings administered from Admin Role.",
        url="/admin/property",
        audience="Administrator",
        related=("admin-dashboard",),
        keywords="property listings",
    ),
    _t(
        "integration-settings",
        "Integration Settings",
        "bi-plug",
        "admin",
        "Admin Role → Integration Settings",
        "SMTP, WhatsApp, and other connectors. Health tab explains failed Dashboard banners.",
        url="/admin/integrations",
        audience="Administrator",
        related=("communication-center", "dashboard"),
        keywords="smtp whatsapp integration settings",
    ),
    _t(
        "dynamic-fields",
        "Dynamic master fields",
        "bi-ui-checks-grid",
        "masters",
        "Masters (field layout)",
        "Administrators can add extra fields on selected masters. Layout changes do not alter GST, WDV, or ledger formulas.",
        url="/masters/item",
        audience="Administrator",
        related=("item-master", "customer-master"),
        keywords="dynamic master fields extra columns",
    ),
)


__all__ = ["MORE_TOPICS"]
